version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MySQL_USER: root
      MYSQL_DATABASE: flourish-crud
    ports:
      - "3307:3306"
  testdb:
    image: mysql:8.0
    container_name: testdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MySQL_USER: root
      MYSQL_DATABASE: flourish-crud-test
    ports:
      - "3308:3306"